### ISSUE TITLE
Access denied error when calling `arc.ws.send` within Lambda on AWS

### ISSUE THREAD

**Issue by andybee** [architect/functions#130]
When my default WebSocket Lambda is invoked, it attempts to send the received message to all other connected client:

```
const arc = require('@architect/functions');

exports.handler = async function handler(payload) {
  const data = await arc.tables();
  const { Items: clients } = await data.connections.scan({});
  const { body: json, requestContext: { connectionId: self } } = payload;
  const body = JSON.parse(json);
  await Promise.all(clients.map(({ connectionId: id }) => {
    if (id === self) {
      return;
    }
    const message = { id, payload: body };
    arc.ws.send(message);
  }));
  return { statusCode: 200 };
}
```

This works locally in Sandbox, but within AWS it throws an error:

```
AccessDeniedException: User: arn:aws:sts::<id>:assumed-role/<project>Staging-Role-<id>/<project>Staging-WebsocketDefault-<id> is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:eu-west-1:********9001:<id>/staging/POST/@connections/@connections/Bw91Ye3FjoECFKw%3D
````

(I've stripped some of the IDs out of that for obvious reasons).

Unsure if this is a `functions` issue invoking the wrong thing, or `deploy`/IAM related?

**Comment by andybee** [comment]
I've tried adding an IAM inline permission to the Arc-created role with allow invocation on any resource:

```
"Effect": "Allow",
"Action": [
  "execute-api:Invoke",
  "execute-api:ManageConnections"
],
"Resource": "*"
```

and I now get a new error:

```
NotFoundException: No method found matching route @connections/@connections/Bw99tfrtjoECJ-Q= for http method POST.
```

I can't tell if that ID looks right, or is malformed? Could it be `@architect/functions` is making a malformed request, which would cause the initial security error, then with relaxed security shows the real error that it's hitting the wrong thing...?

**Comment by andybee** [comment]
The workaround I've found for my project is to copy the function internal to `arc.ws.send` function locally in to my function's own code and adapt the args to allow me to supply the event, too. Then everything works. Truth be told, I'm unsure of how the `event` otherwise gets in to `arc.ws.send` inside the module? Could this be the issue?

**Comment by brianleroux** [comment]
Hey! I am reproducing the weird `@connections/@connections` error and have escalated w AWS. Sorry this took so long to respond. Will update here when I know more.

**Comment by brianleroux** [comment]
also! we have a bug with the generated IAM role. Here's a macro that patches it:

```
// add to `src/macros/ws.js` and add `@macros` with `ws` on one line to the `.arc`

// adds websocket policy to Role
module.exports = function fixpermission(arc, cfn, stage) {

  delete cfn.Resources.RoleReflectionPolicy

  cfn.Resources.WebSocketPolicy = {
    Type: 'AWS::IAM::Policy',
    DependsOn: 'Role',
    Properties: {
      PolicyName: 'ArcWebSocketPolicy',
      PolicyDocument: {
        Statement: [{
          Effect: 'Allow',
          Action: [
            'execute-api:Invoke',
            'execute-api:ManageConnections'
          ],
          Resource: [
            {"Fn::Sub": [
              'arn:aws:execute-api:${AWS::Region}:*:${api}/*',
              {api: {Ref: 'WS'}}
            ]}
          ]
        }]
      },
      Roles: [{Ref: 'Role'}]
    }
  }

  return cfn
}
```

**Comment by brianleroux** [comment]
thx for hanging in there. these issues should be resolved with:

- `@architect/architect@6.0.21`
- `@architect/functions@3.4.6`

**Comment by andybee** [comment]
Just in time for Halloween...
![IMG_0021](https://user-images.githubusercontent.com/113305/67725136-2970f980-f9d9-11e9-90d3-414f5165943a.png)

**Comment by andybee** [comment]
Just in time for Halloween...
![IMG_0021](https://user-images.githubusercontent.com/113305/67725213-79e85700-f9d9-11e9-90a5-5fbc0f627d81.jpeg)

**Comment by brianleroux** [comment]
# 🎃
