### ISSUE TITLE
Get table name using tables function

### ISSUE THREAD

**Issue by darbio** [architect/functions#138]
In previous versions of architect we could get the table name using `data._name('users')`. This appears to be removed in version 6.

The helper was great when we had to drop down and use AWS SDK's or needed finer control of the AWS operation, such as when wanting to add condition expressions etc.

How do I achieve the following in version 6?

```
const tableName = 'users';

const data = await arc.tables();
const tableName = data._name(tableName);

await data._doc.put({
    TableName: tableName,
    Item: {
       emailAddress: 'user@domain.tld'
    },
    ConditionExpression: 'attribute_not_exists(emailAddress)',
});
```

**Comment by brianleroux** [comment]
Putting some thought into this finally and think we need a new API. Moving to CloudFormation means table names get generated (which is good!) but also a bit of a pain as you are now experiencing (sorry!). We currently internally store the names in SSM and look them up when needed. Here's where we do that: https://github.com/architect/functions/blob/master/src/tables/lookup-tables.js

Idea moving forward would be an interface to only look these up once.

```javascript
let data = await arc.tables()
let names = await data.reflect() // returns {arcfilename: 'generated-tablename'}
```

What do you think ?

**Comment by brianleroux** [comment]
Cool, hopefully get this mainline soon! Have a few things to coordinate and test before merging to master but shouldn't be more than a day or two. Thanks!
