### ISSUE TITLE
Allow parameters to be passed to table.put

### ISSUE THREAD

**Issue by darbio** [architect/functions#144]
When using the `put` function to add an item to dynamodb, it would be useful to be able to add parameters to the request (e.g. ConditionExpression etc.). This would allow us to use put in a manner that does not overwrite a previous item if one already exists in the table.

```
var params = {
  Item: {
    partitionKey: partitionKey,
    sortKey:      sortKey,
    data:         data
  },
  ConditionExpression: 'attribute_not_exists(partitionKey) AND attribute_not_exists(sortKey)'
};
```

This would stop us having to do the following (which consumes RCUs) when inserting new items:

```
let data = await arc.tables();

const exists = await data.users.get({ _id: id })
if (exists) {
    throw new Error(`User ${model._id} already exists.`);
}

await data.users.put(model);
```

**Comment by brianleroux** [comment]
This is good feedback: thank you. Agree we need to have a way to do this. 

As a workaround in the meantime for more complex queries recommend dropping to the [DynamoDB.DocumentClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html) directly; we cache an instance on the result of tables:

```javascript
let data = await arc.tables()
let result = await data.doc.scan({TableName}).promise()
```

The problem with this is finding out `TableName` which is generated by CloudFormation; we currently do not have an official API to reflect these but the pattern is to store is SSM. Here is how we do it internally https://github.com/architect/functions/blob/master/src/tables/lookup-tables.js

Would love thoughts/feedback on reflecting the table names… could see maybe doing this:

```javascript
let data = await arc.tables()
let tables = await data.reflect() // returns {arcfilename: 'generated-name'}
```

**Comment by darbio** [comment]
I can see that working (and fixing #138 - not being able to find table name).

Alternatively a breaking change to the `data.table.put` method to bring it more in line with the other methods may be less confusing:

```
data.table.put({
  Item: {
    partitionKey: partitionKey,
    sortKey:      sortKey,
    data:         data
  },
  ConditionExpression: 'attribute_not_exists(partitionKey) AND attribute_not_exists(sortKey)'
});
```

I know that this removes some of the 'nice' around the primitive, but it's required for the other methods (`query`, `scan`, `update` etc.) anyway.

Backwards compatibility could be maintained by checking the shape of the parameter passed to `put`.

**Comment by brianleroux** [comment]
yeah I'm into exploring that; just added that reflect method per above if you want to try it out

```
cd path/to/lambda
npm i @architect/functions@RC
```

**Comment by darbio** [comment]
This is working as described. Thanks.

**Comment by zachrip** [comment]
I know there's a way to drop down and use the document client itself, however when you mix architect with typescript it's really unfavorable - could this possibly be revisited? I'd be happy to supply a pr if it would be approved. Thanks :D
