### ISSUE TITLE
Restore _name functionality

### ISSUE THREAD

**Issue by brianleroux** [architect/functions#158]
**Describe the issue**
A clear and concise description of the bug

**Steps to reproduce**
4. See error that says '....'

**Expected behavior**
A clear and concise description of what you expected to happen

**Screenshots**
If applicable, add screenshots to help explain your problem

**Desktop**
Please complete the following information (if appropriate):

**Mobile**
Please complete the following information (if appropriate):

**Additional context**
Add any other context or notes about the problem here

**Comment by defionscode** [comment]
fixed via https://github.com/architect/functions/commit/3d9a913515fedd44c7728740f4691f4ceaadb91e
