### ISSUE TITLE
events.publish fails with > 10 topics 

### ISSUE THREAD

**Issue by dduran1967** [architect/functions#165]
**Describe the issue**
Calling arc.events.publish returns 'topic not found' on topics after the first ten returned from SSM.

**Steps to reproduce**
1. create an arc with 11 topics
2. create a function that calls each topic by name
3. one will fail.

I seems that ssm.getParametersByPath is limited to 10 results, which breaks in 

```javascript
function lookupTopics(callback) {
  let ssm = new aws.SSM
  let Path = `/${process.env.ARC_CLOUDFORMATION}`
  ssm.getParametersByPath({Path, Recursive:true}, function done(err, result) {
    if (err) callback(err)
    else {
      let topic = param=> param.Name.split('/')[2] === 'events'
      let topics = result.Parameters.filter(topic).reduce((a, b)=> {
        a[b.Name.split('/')[3]] = b.Value
        return a
      }, {})
      callback(null, result.Parameters)
    }
  })
}
```

**Comment by brianleroux** [comment]
think this is resolved in `@architect/functions@latest` please confirm!
