### ISSUE TITLE
ws issues with arc-example-ws

### ISSUE THREAD

**Issue by wookiehangover** [architect/functions#24]
Howdy :wave:

I ran into a couple of issues getting the `arc-example-ws` repo working. I was able to get the example app working eventually, but my best guess is that the problems I ran into stem from this project.

* `src/ws/index.js` requires `aws-sdk` , but it's declared as a dev dependency in @architect/functions, so it's not available if you just do a normal npm install
  * worked around this by manually installing `aws-sdk` across `src/ws/*`
* `AccessDeniedException` is thrown because the role assigned to the `src/ws/*` lambda was missing the `execute-api:ManageConnections` permission (full error message below)
  * worked around this by manually adding that permission through the IAM console
  * I'm assuming that I didn't skip any steps to get here (following the docs), but I guess that could be possible?

### Errors
<details>
<summary>Missing aws-sdk error log</summary>
<pre><code>~\code\clones\arc-example-ws $ npx logs src/ws/ws-default
        app ~ test-ws
     region ~ us-west-2
    profile ~ xxx
    version ~ 5.0.7

Feb 03, 05:36:41 PM
ws-default called with { requestContext: 
   { routeKey: '$default',
     authorizer: '',
     messageId: 'UjSOXedLvHcCH1Q=',
     integrationLatency: '',
     eventType: 'MESSAGE',
     error: '',
     extendedRequestId: 'UjSOXFftvHcFiow=',
     requestTime: '04/Feb/2019:01:36:40 +0000',
     messageDirection: 'IN',
     stage: 'staging',
     connectedAt: 1549244197491,
     requestTimeEpoch: 1549244200779,
     identity: 
      { cognitoIdentityPoolId: null,
        accountId: null,
        cognitoIdentityId: null,
        caller: null,
        sourceIp: '73.92.10.73',
        accessKey: null,
        cognitoAuthenticationType: null,
        cognitoAuthenticationProvider: null,
        userArn: null,
        userAgent: null,
        user: null },
     requestId: 'UjSOXFftvHcFiow=',
     domainName: 'kasodogei2.execute-api.us-west-2.amazonaws.com',
     connectionId: 'UjSN2edEvHcCH1Q=',
     apiId: 'kasodogei2',
     status: '' },
  body: '{"text":"hullo"}',
  isBase64Encoded: false }

Feb 03, 05:36:41 PM
 TypeError: aws.ApiGatewayManagementApi is not a constructor 
Object.send (/var/task/node_modules/@architect/functions/src/ws/index.js:54:23)
ws (/var/task/index.js:15:23)
</pre></code>
</details>

<details>
<summary>Missing execute-api:ManageConnections permission error log</summary>
<pre><code>
Feb 03, 05:36:41 PM
Billed Duration: 100 ms
Memory Size: 1152 MB
Max Memory Used: 38 MB

Feb 03, 05:55:44 PM
ws-default called with { requestContext: 
   { routeKey: '$default',
     authorizer: '',
     messageId: 'UjVA_ed1PHcCEww=',
     integrationLatency: '',
     eventType: 'MESSAGE',
     error: '',
     extendedRequestId: 'UjVA_EL5PHcFeyg=',
     requestTime: '04/Feb/2019:01:55:43 +0000',
     messageDirection: 'IN',
     stage: 'staging',
     connectedAt: 1549245340677,
     requestTimeEpoch: 1549245343908,
     identity: 
      { cognitoIdentityPoolId: null,
        accountId: null,
        cognitoIdentityId: null,
        caller: null,
        sourceIp: '73.92.10.73',
        accessKey: null,
        cognitoAuthenticationType: null,
        cognitoAuthenticationProvider: null,
        userArn: null,
        userAgent: null,
        user: null },
     requestId: 'UjVA_EL5PHcFeyg=',
     domainName: 'kasodogei2.execute-api.us-west-2.amazonaws.com',
     connectionId: 'UjVAeedwPHcCEww=',
     apiId: 'kasodogei2',
     status: '' },
  body: '{"text":"hullo"}',
  isBase64Encoded: false }

Feb 03, 05:55:44 PM
 AccessDeniedException: User: arn:aws:sts::226364732856:assumed-role/arc-role/test-ws-staging-ws-default is not authorized to perform: execute-api:ManageConnections on resource: arn:aws:execute-api:us-west-2:********2856:kasod
ogei2/staging/POST/@connections/{connectionId} 
Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)
Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
/var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)</pre></code></details>

I did end up getting the example app working, but it took a little bit of debugging to get to `hello world`.

Thanks! 🤗

**Comment by ryanblock** [comment]
We did a ton of work in WebSockets over the years, I'm guessing we've resolved issues (and that example repo is prob hella stale). Pls reopen if we need to take another look though! <3
