### ISSUE TITLE
Multi-value query string parameters behave differently in sandbox

### ISSUE THREAD

**Issue by defionscode** [architect/functions#257]
**Describe the issue**

Given logic like this

```js
    const querystring = require('querystring')
    const qs = querystring.stringify({
      ids = [1,2,3,4]
    })
    const res = await fetch(`${rootUrl}records/TEST?${qs}`, { method, headers })

// qs evalues to "ids=1&ids=2&ids=3&ids=4"
```

you would expect for the underlying lambda to process it the same way

**Expected behavior**

while using `arc.http.asyc`

I would expect the value of  `req.query` to be consistent

However.

In sandbox `req.query.ids` is indeed the array of ids as supplied

but when `rootUrl` is an actual API Gateway endpoint, `req.query.ids` is not an array. It holds the value of the last element in the `ids` array. I ended up needing to use `req.multiValueQueryStringParameters`.

I think what makes sense is to make it so that `req.multiValueQueryStringParameters.ids` is the only way to get these types of query strings and make sandbox behave this way too.

**Comment by defionscode** [comment]
also `multiValueQueryStringParameters` is simply not available in sandbox

**Comment by defionscode** [comment]
fixed in https://github.com/architect/sandbox/pull/295

**Comment by ryanblock** [comment]
Thanks @defionscode!
