### ISSUE TITLE
old school res({ html }) borken

### ISSUE THREAD

**Issue by brianleroux** [architect/functions#270]
few use or like this interface so low priority

**Comment by ryanblock** [comment]
Here's the test that make sure that one continues to work: https://github.com/architect/functions/blob/sns/test/unit/src/http/http-res-test.js#L268

Are there steps to repro?

**Comment by ryanblock** [comment]
@ShawnHosea do you recall which repo was broken?

**Comment by ShawnHosea** [comment]
Not sure but Brian and I were working on this repo around that time.

https://github.com/architect/destroy
