### ISSUE TITLE
Websocket responses using only connectionId 

### ISSUE THREAD

**Issue by mikemaccana** [architect/functions#33]
**Describe the bug**
Per Twitter discussion between @brianleroux and I: currently to respond to a websocket, we do:

`arc.ws().send()`

`arc.ws()` takes a `connectionId` and an `apiId`, and `send()` takes a `connectionId` 

It would be better to:

 - Only require the `connectionId` once 
 - Cache `apiId` if possible

Something like `arc.ws.send(connectionId, payload)` would be great. This means we could store connectionId in DynamoDB / DocumentDB and use it to respond to websockets from outside the `/src/ws` - for example we could have an HTTP POST (called from an admin panel via `/src/https/post-xxx-xxx-xxx`) that sends a particular message to a subset of connected users via websockets.

B seemed to like this, so filing it here!

> I might be able to get rid of that param (`apiId`)
> By looking it up once and caching
> We do that for events and queues
> Hmm, ya we should
> xnoɹǝʃ uɐıɹq 🐻
> (thx for talking thru this w me)

**Comment by brianleroux** [comment]
haven't documented / tested (yet) but in the new cloudformation based version we now cache the urls in parameter store so we can support `arc.ws.send({id, payload})` cleanly !

you can check the code here https://github.com/architect/functions/tree/v4/src/ws

just hacking/slashing it together. next step is to ensure backwards compat before merging into mainline. then we can get to finishing the docs/tests …and then release! 🚀

**Comment by mikemaccana** [comment]
Sweet! I'm going to bang on this later today!

**Comment by mikemaccana** [comment]
Note to self: npm install git://github.com/architect/functions#v4
