### ISSUE TITLE
Deploy failed after following quickstart

### ISSUE THREAD

**Issue by jbergens** [architect/functions#421]
**Describe the issue**
Ran "arc init" and tried "arc sandbox" and both worked. Then just tried to do "arc deploy" and it failed. Tried to make sure I hade the correct AWS credentials and it seems to start to create things but ends with an error. It also fails when I try a dry-run.

    arc deploy --name dev-jb --dry-run
      App ~ arclab1
      Region ~ eu-north-1
      Profile ~ ....
     Version ~ Architect 8.5.7
         cwd ~ C:\...\arclab1
    Deploy` [dry-run] Starting dry run!
    Deploy [dry-run] Initializing deployment
      | Stack ... Arclab1StagingDevX
      | Bucket .. N/A (dry-run)
    √ Hydrate Finished checks, nothing to hydrate
    C:\...\v12.20.0\node_modules\@architect\architect\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

    Error [TypeError]: callback is not a function
      at done (C:\...\v12.20.0\node_modules\@architect\architect\node_modules\@architect\deploy\src\sam\index.js:152:11)
      at done  C:\...\v12.20.0\node_modules\@architect\architect\node_modules\@architect\deploy\src\sam\compat\index.js:52:10)
      at end (C:\...\v12.20.0\node_modules\@architect\architect\node_modules\run-series\index.js:11:15)
      at done (C:\...\v12.20.0\node_modules\@architect\architect\node_modules\run-series\index.js:14:10)
      at each (C:\...\v12.20.0\node_modules\@architect\architect\node_modules\run-series\index.js:19:43)
      at Array.getEventsParam (C:\...\v12.20.0\node_modules\@architect\architect\node_modules\@architect\deploy\src\sam\compat\index.js:48:12)
      at each (C:\dev\nvm\v12.20.0\node_modules\@architect\architect\node_modules\run-series\index.js:20:24)

**Steps to reproduce**
1. `arc init`
2. `arc deploy`
4. See error that says 'Error [TypeError]: callback is not a function'

**Expected behavior**
A message that the stack has been built on AWS

**Desktop**
Please complete the following information (if appropriate):
 - OS: Windows 10
 - Node: 12.20.0
 - AWS Region: eu-north-1

**Comment by filmaj** [comment]
Damnit, this is a bug I introduced yesterday with a change in how deploy tasks are run (changed to waterfall instead of series).

Working on a fix, will publish a patch release ASAP

**Comment by jbergens** [comment]
Thanks for the quick response!

Can I just upgrade arc or do I need to do something special?

**Comment by filmaj** [comment]
I am working on getting a new arc release; the fix will be available in arc 8.5.8, which I should be able to publish in ~10 mins or so. I will comment here once it is live.

**Comment by filmaj** [comment]
arc version 8.5.8 is now live on npm, please upgrade to fix this issue, super sorry for the inconvenience!

**Comment by jbergens** [comment]
It works now! Thanks!
