### ISSUE TITLE
Functions 4: arc.ws.send() hangs lambda in sandbox

### ISSUE THREAD

**Issue by mikemaccana** [architect/functions#44]
Following on from https://github.com/architect/functions/issues/33 I've been testing Arc Functions v4.

Using `6c43f8bc70190f8ede03791ebcc3eca40864bfbf` from git, `await arc.ws.send(connectionID, payload)` will break a lambda in the sandbox

No logging, including `console.log()` before the `arc.ws.send()`, will be shown if the `arc.ws.send()` is enabled

Inspecting the `arc.ws.send()`code it looks like the promise is missing from `arc.ws.send()`, so wrapping it in a promisify:

```
let arc = require('@architect/functions'),
  makePayload = require('@architect/shared/make-payload'),
  util = require("util");

const webSocketSend = util.promisify(arc.ws.send);

require('@architect/shared/globals')

exports.handler = async function webSocketConnect(event) {
  let connectionID = event.requestContext.connectionId
  log(`Sending chat default greeting to new client at connection ID: ${connectionID}`)
  var payload = makePayload(`Hey there whats up!`, 'Mike')
  // BUG - if uncommented this will never return
  // await webSocketSend(connectionID, payload)
  log(`ws connect finished`)
  return {
    status: OK
  }
}
```

(Obviously I've tried it without the promisify too)

How can I make `arc.ws.send()` work in the sandbox?

**Comment by mikemaccana** [comment]
Note if I uncomment `await webSocketSend(connectionID, payload)` I will get a response, just much. much later - it looks like there's a timeout occuring: 

```
Sending chat default greeting to new client at connection ID: 46618dcc-3475-4d4e-b1ce-5b4a744b4928
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Socket.socketOnEnd (_http_client.js:426:9)
    at Socket.emit (events.js:203:15)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

Do you have the same thing?

**Comment by mikemaccana** [comment]
This works now. Suspect it may have been me, combined with https://github.com/architect/functions/issues/135 meaning the error wasn't being shown.

**Comment by brianleroux** [comment]
(should be fixed but feel free to reopen!)
