### ISSUE TITLE
brotli compression breaks Sandbox livereload

### ISSUE THREAD

**Issue by tbeseda** [architect/functions#525]
`@architect/functions` brotli compression interferes with Sandbox livereload

This line always evaluates to `true`
https://github.com/architect/sandbox/blob/main/src/http/invoke-http/utils/livereload.js#L6

My thought would be to disable brotli (compression in general?) in testing (and staging?).
And/or an option to disable compression ala https://github.com/architect/architect/issues/1341

**Comment by ryanblock** [comment]
Fixed in Sandbox 5.3.1!
