### ISSUE TITLE
Redirect `/staging` to `/staging/` in http proxy 

### ISSUE THREAD

**Issue by gr2m** [architect/functions#65]
This is a follow up to this thread: https://architecture-as-text.slack.com/archives/C6BGT0D08/p1566800132296400

> I wonder it would be possible to redirect `<https://mzix1huilh.execute-api.us-west-2.amazonaws.com/staging>` automagically to `<https://mzix1huilh.execute-api.us-west-2.amazonaws.com/staging/>`? With the former loading the JS/CSS assets breaks as the paths need to be relative, it tries to load `<https://mzix1huilh.execute-api.us-west-2.amazonaws.com/index.js>` instead of `<https://mzix1huilh.execute-api.us-west-2.amazonaws.com/staging/index.js>`

**Is your feature request related to a problem? Please describe.**

When referencing e.g. `<script src="index.js"></script` in `public/index.html`, then `/index.js` is loaded instead of `/staging/index.js` if the opened URL is https://mzix1huilh.execute-api.us-west-2.amazonaws.com/staging.

**Describe the solution you'd like**

https://mzix1huilh.execute-api.us-west-2.amazonaws.com/staging would ideally redirect to https://mzix1huilh.execute-api.us-west-2.amazonaws.com/staging/

**Describe alternatives you've considered**

Maybe try to redirect using [`history.pushState()`](https://developer.mozilla.org/en-US/docs/Web/API/History_API) before loading any assets, but not sure if that will work, didn't have a chance to try

**Comment by brianleroux** [comment]
(Just fyi the new HTTP API based Architect no longer creates annoying /staging and /production url parts.)
