### ISSUE TITLE
[Low Pri] arc.static will break if NODE_ENV set to something unexpected

### ISSUE THREAD

**Issue by mikemaccana** [architect/functions#72]
**Describe the issue / Steps to reproduce**

If the sandbox is launched where `NODE_ENV` is set to something unexpected (in my case, I used `tunnelled`, arc.static()` will return non-usable URLs. 

This happened when I hapepned to reuse a terminal from another node app. 

The issue comes from:

https://github.com/architect/functions/blob/master/src/static/index.js#L22

This defines 

    let runningLocally = !env || env === 'testing' || process.env.ARC_LOCAL

Which fails in the case where `NODE_ENV` exists but isn't a known value. Other parts of arc, like `arc.http.helpers.url` use different parsing logic, looking for explicit strings then falling back.

 

## Options to fix

Ideally, have one function only that is called from anywhere that wants to look up the env, fixing issues like this (also allowing changes to be made more rapidly because one place needs to be modified, rather than many.)  This should be like `arc.http.helpers.url` use different parsing logic, looking for explicit strings then falling back.

**Comment by brianleroux** [comment]
reimplemented arc.static to always return the api gateway _static url

https://github.com/architect/functions/blob/master/src/static/index.js#L22

(which should fix this issue!)
